### ISSUE TITLE
RuntimeError: PytorchStreamReader failed reading zip archive: failed finding central directory

### ISSUE THREAD

**Issue by iT-Boyer** [hizkifw/WebChatRWKVstic#4]
```
Importing modules...

**************************************
WARN: CUDA not available, will use CPU
If you want to use CUDA, try running this command:

  pip install torch --extra-index-url https://download.pytorch.org/whl/cu117 --upgrade

For more information, see: https://pytorch.org/get-started/locally/
*************************************

-> Using model models/RWKV-4-Pile-3B-ctx4096.pth
Traceback (most recent call last):
  File "/Users/boyer/hsg/WebChatRWKVstic/main.py", line 25, in <module>
    import model
  File "/Users/boyer/hsg/WebChatRWKVstic/model.py", line 173, in <module>
    model = RWKV(
  File "/Users/boyer/miniconda/lib/python3.10/site-packages/rwkvstic/load.py", line 62, in RWKV
    ops, weights = loadWeights(mode, path, *args, **kwargs)
  File "/Users/boyer/miniconda/lib/python3.10/site-packages/rwkvstic/helpers/loadWeights.py", line 14, in loadWeights
    w: Dict[str, torch.Tensor] = torch.load(
  File "/Users/boyer/miniconda/lib/python3.10/site-packages/torch/serialization.py", line 797, in load
    with _open_zipfile_reader(opened_file) as opened_zipfile:
  File "/Users/boyer/miniconda/lib/python3.10/site-packages/torch/serialization.py", line 283, in __init__
    super().__init__(torch._C.PyTorchFileReader(name_or_buffer))
RuntimeError: PytorchStreamReader failed reading zip archive: failed finding central directory
(base)
```

**Comment by iT-Boyer** [comment]
重新下载 解决了问题：https://huggingface.co/BlinkDL/rwkv-4-pile-3b/resolve/main/RWKV-4-Pile-3B-20221110-ctx4096.pth
